### ISSUE TITLE
no instruction when compiling n-store

### ISSUE THREAD

**Issue by zhuguoliang** [swapnilh/whisper#11]
Hi, dear whisper creaters!

I am exploring the world of whisper and find that build failed. 

![image](https://cloud.githubusercontent.com/assets/9863649/24136599/87dc000a-0e4a-11e7-861c-cfbab782ecb6.png)

I think it maybe because different clfulsh support on different processors?

**Comment by zhuguoliang** [comment]
This can be solved by modifying common/libpm.h to change clflushopt to clflush

The reason is because my sandybridge processor does not support CLFLUSHOPT.

**Comment by swapnilh** [comment]
Thanks for fixing it, I have put in a warning in the README now..
