### ISSUE TITLE
Monitored TOTAL EPOCH COUNT is always zero

### ISSUE THREAD

**Issue by zhuguoliang** [swapnilh/whisper#12]
Hi, dear whisper creaters!

As a newbie for NVML, I am very interested into whisper and I try to run every benchmark in whisper.

Now I found that there is no epoch num reported.

![image](https://cloud.githubusercontent.com/assets/9863649/24147322/a06d3b00-0e74-11e7-8e0e-21598a405efb.png)

I want to know how to enable EPOCH profiling. Thanks!

**Comment by snalli** [comment]
When tracing is disabled, the system can't keep track of epochs.
