### ISSUE TITLE
no free memory of size 128 available for kv-echo

### ISSUE THREAD

**Issue by zhuguoliang** [swapnilh/whisper#13]
Hi, dear creatter of WHISPER.

I compiled with build.sh in dir kv-echo and run with default run.sh --large

![image](https://cloud.githubusercontent.com/assets/9863649/24152222/fb381ea4-0e85-11e7-98d4-ed608299af0d.png)

It hinted me to look for file include/pm_instr.h.

I checked and found a defination:
> #define PSEGMENT_RESERVED_REGION_SIZE (1UL * 1024 * 1024 * 1024)

It looks just like what I saw when experimenting with DAX in linux, does this mean that this correspond to the reserved PMEM address space during kernel boot?

**Comment by zhuguoliang** [comment]
I checked and it is true that echo relies on reserving memory as we did for DAX in linux.

I think it is better this is added in the manual for other users.

Now it is working now.

**Comment by swapnilh** [comment]
The macro 'PSEGMENT_RESERVED_REGION_SIZE' denotes the size of the allocated Persistent Memory pool. It is created during the benchmark execution if it does not already exist. 
I am adding this issue in the README as well.
