### ISSUE TITLE
Memcached won't compile 

### ISSUE THREAD

**Issue by zhuguoliang** [swapnilh/whisper#14]
When compiling mnemosyne for memcached with command: scons 

> --build-bench=memcached

 I went to a strange bug report
![image](https://cloud.githubusercontent.com/assets/9863649/24196351/6e077ae4-0f38-11e7-962c-64526dee42a1.png)

**Comment by swapnilh** [comment]
What version of gcc are you using to compile this?

**Comment by zhuguoliang** [comment]
gcc version 5.3.0

**Comment by swapnilh** [comment]
That is weird, I just tried to compile memcached with the same command and using gcc-5.3.0, and could not reproduce this issue. I was able to build successfully. Let me see what else could be an issue..

**Comment by swapnilh** [comment]
Could you run this and paste the output:
scons --build-bench=memcached --verbose

**Comment by zhuguoliang** [comment]
It works with stamp-kozy in command 

> scons --build-bench=stamp-kozy

Hence benchmark vacation is OK with this

**Comment by zhuguoliang** [comment]
Here is the result 
![image](https://cloud.githubusercontent.com/assets/9863649/24200989/bc0e5544-0f49-11e7-81be-92957d24a07f.png)

**Comment by swapnilh** [comment]
Just to be clear, doing '/root/bin-wrapper/gcc -v' results in 5.3.0?

**Comment by zhuguoliang** [comment]
Yes, since I do not make 5.3.0 mess with the original GCC, I wrap it here

**Comment by swapnilh** [comment]
Could you show what is the result of these two commands:
echo $LD_LIBRARY_PATH
echo $LD_PRELOAD

Maybe there is something there..

Perhaps, you could try with gcc-6.1 too?

**Comment by zhuguoliang** [comment]
![image](https://cloud.githubusercontent.com/assets/9863649/24201267/88d27092-0f4a-11e7-8cae-76d060480971.png)

OK, I am downloading gcc-6.1 now

**Comment by swapnilh** [comment]
When you do gcc -v for gcc-5.3.0, what is the complete output? I want to see what it is 'Configured with' specifically?

**Comment by zhuguoliang** [comment]
![image](https://cloud.githubusercontent.com/assets/9863649/24201444/ff36d5b6-0f4a-11e7-9335-6a953e626409.png)

**Comment by swapnilh** [comment]
So my gcc-5.3.0 is configured thus-
Configured with: ../gcc-5.3.0/configure --prefix=/s/gcc-5.3.0/amd64_ubu14 --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,fortran,go --disable-dssi --enable-plugin --with-cpu=generic --disable-multilib

I checked a few of these flags which looked suspicious, but couldn't find anything linked to the error.

Perhaps you could also configure gcc again and rebuild it (https://gcc.gnu.org/install/configure.html) with these flags (without the  --prefix=/s/gcc-5.3.0/amd64_ubu14). I would do this after trying gcc-6.1.

**Comment by snalli** [comment]
This has nothing to do with compiler version or flags. Just make sure you are using one that supports stm, and I will add some code and get back to you.

--
Sanketh Nalli
Graduate Student, Computer Sciences
University of Wisconsin-Madison, USA
pages.cs.wisc.edu/~sankey/

________________________________

**Comment by zhuguoliang** [comment]
STM is already supported since GCC 4.7, will you please be more specific on this? 
Currently I use gcc 5.3 for compiling memcached.

**Comment by snalli** [comment]
i think i fixed it. just update whisper and re-compile mnemosyne.


./script -u

./script -w memcached -c -s -b


--
Sanketh Nalli
Graduate Student, Computer Sciences
University of Wisconsin-Madison, USA
pages.cs.wisc.edu/~sankey/<http://pages.cs.wisc.edu/~sankey/><http://pages.cs.wisc.edu/~sankey/>
________________________________

**Comment by snalli** [comment]
if it doesn't work, can you tell me the version of glibc on your system ?


ldd --version


paste the output here.


--
Sanketh Nalli
Graduate Student, Computer Sciences
University of Wisconsin-Madison, USA
pages.cs.wisc.edu/~sankey/<http://pages.cs.wisc.edu/~sankey/><http://pages.cs.wisc.edu/~sankey/>
________________________________

**Comment by zhuguoliang** [comment]
This is a problem of glibc, by updating my glibc to glibc-2.23 memcached can be successfully compiled. (I have merged your pull request  #17  by hand.)
However, a new issue emerged when compiling stamp-kozy,

![image](https://cloud.githubusercontent.com/assets/9863649/24236262/27203d10-0fdc-11e7-80a8-a2fc9d2de57b.png)

**Comment by zhuguoliang** [comment]
Maybe it is better to provide a tool chain recommandation such as gcc version request and glibc version on your system in README.

Current tool suite I use is GCC 5.3.0 with glibc 2.23

I guess your tool chain is GCC 6.2 with glibc 2.19?

**Comment by snalli** [comment]
I have 6.2.1 & 2.23 and 5.3 &  2.19

--
Sanketh Nalli
Graduate Student, Computer Sciences
University of Wisconsin-Madison, USA
pages.cs.wisc.edu/~sankey/

________________________________

**Comment by snalli** [comment]
I'll do that.

I pushed some code for this. can you pull now and tell me if u can compile ?


--
Sanketh Nalli
Graduate Student, Computer Sciences
University of Wisconsin-Madison, USA
pages.cs.wisc.edu/~sankey/<http://pages.cs.wisc.edu/~sankey/><http://pages.cs.wisc.edu/~sankey/>
________________________________

**Comment by zhuguoliang** [comment]
I am back in bed, I will compile in 8 hours


发自网易邮箱大师
On 03/24/2017 00:53, snalli wrote:
I'll do that.

I pushed some code for this. can you pull now and tell me if u can compile ?


--
Sanketh Nalli
Graduate Student, Computer Sciences
University of Wisconsin-Madison, USA
pages.cs.wisc.edu/~sankey/<http://pages.cs.wisc.edu/~sankey/><http://pages.cs.wisc.edu/~sankey/>
________________________________

**Comment by zhuguoliang** [comment]
Both memcached and stamp-kozy can be built with no errors.

Thanks!
