### ISSUE TITLE
Fatal error when executing scons in mnemosyne dir

### ISSUE THREAD

**Issue by Meditator-hkx** [swapnilh/whisper#20]
When I run 'scons', it reports an error as follows:

```
library/pmalloc/include/alps/include/alps/commen/log.hh:33:33: fatal error:boost/log/trivial.hpp: No such file or directory

#include <boost/log/trivial.hpp>
```
I guess it happened because I didn't create a mount point backed by persistent memory. Would you kindly tell me what went wrong with me and how it's possible to create a mount point with pure DRAM?

Thanks!

**Comment by snalli** [comment]
sorry, please get the boost library. it has nothing to do with mountpoints.
